import requests, json, sys, urllib.parse
from datetime import datetime, timedelta

sys.stdout.reconfigure(encoding='utf-8')

SUPABASE_URL = 'https://cwqghiqykohefaggedjl.supabase.co'
SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cWdoaXF5a29oZWZhZ2dlZGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwMjUyMjEsImV4cCI6MjA5NjYwMTIyMX0.3a3hRcNdmYQCtjYjBroAT6df1T_7oz-XWUeD3wagYw8'

ARABIC_DIGITS = str.maketrans('٠١٢٣٤٥٦٧٨٩', '0123456789')
def norm_date(s):
    if not s or not isinstance(s, str): return s or ''
    s = s.replace('\u200f', '').replace('\u200e', '').strip()
    s = s.translate(ARABIC_DIGITS).strip()
    s = s[:10]
    parts = s.split('/')
    if len(parts) == 3:
        d, m, y = parts
        if len(y) == 4:
            try: return f'{y}-{int(m):02d}-{int(d):02d}'
            except Exception: return s
    try: return datetime.strptime(s[:10], '%Y-%m-%d').strftime('%Y-%m-%d')
    except Exception: return s[:10]

def fetchtable(idval):
    url = SUPABASE_URL + '/rest/v1/sync_data?' + urllib.parse.urlencode({'select': 'id,data,updated_at', 'id': 'eq.' + idval})
    r = requests.get(url, headers={'apikey': SUPABASE_KEY, 'Authorization': 'Bearer ' + SUPABASE_KEY})
    if r.status_code != 200:
        print('GET', idval, 'HTTP', r.status_code, r.text[:120])
        return None
    rows = r.json()
    if not rows: return None
    data = rows[0].get('data')
    if isinstance(data, str):
        try: data = json.loads(data)
        except Exception: data = None
    return data

rep = []
def P(*a):
    s = ' '.join(str(x) for x in a)
    print(s); rep.append(s)

ent_m = fetchtable('ent:mealLogs')
plain_m = fetchtable('mealLogs')
ent_ds = fetchtable('ent:dailyStats')
plain_ds = fetchtable('dailyStats')
P('ent:mealLogs     =', len(ent_m) if isinstance(ent_m, list) else ent_m)
P('plain mealLogs   =', len(plain_m) if isinstance(plain_m, list) else plain_m)
P('ent:dailyStats   =', len(ent_ds) if isinstance(ent_ds, list) else ent_ds)
P('plain dailyStats =', len(plain_ds) if isinstance(plain_ds, list) else plain_ds)

def fmt_rec(r):
    return {
        'date': norm_date(r.get('date','')), 'bf': r.get('breakfast'), 'lh': r.get('lunch'),
        'dn': r.get('dinner'), 'autoFilled': r.get('autoFilled'), 'auto': r.get('autoGenerated'),
        'guestBf': r.get('guestBf'), 'guestLh': r.get('guestLh'), 'guestDn': r.get('guestDn'),
        'keys': list(r.keys()),
    }

if isinstance(ent_m, list) and ent_m:
    P('mealLogs record keys:', ','.join(ent_m[0].keys()))
    d2 = {norm_date(r.get('date','')): r for r in ent_m if norm_date(r.get('date',''))}
    days = sorted(d2)
    P('mealLogs range:', days[:3], '...', days[-3:] if len(days) > 3 else '', 'total days', len(days))
    P('--- last 18 meal days (bf/lh/dn/total) ---')
    for d in days[-18:]:
        r = d2[d]
        P(d, '|', r.get('breakfast'), r.get('lunch'), r.get('dinner'),
          'autoFilled' if r.get('autoFilled') else ('auto' if r.get('autoGenerated') else 'manual'))
    P('--- unique (bf==lh==dn) triples distribution ---')
    from collections import Counter
    tri = Counter((r.get('breakfast'), r.get('lunch'), r.get('dinner')) for r in ent_m)
    for t, c in tri.most_common(8):
        P(t, '=>', c)

if isinstance(ent_ds, list) and ent_ds:
    P('dailyStats record keys:', ','.join(ent_ds[0].keys()))
    dd = {norm_date(r.get('date','')): r for r in ent_ds if norm_date(r.get('date',''))}
    dd_days = sorted(dd)
    P('dailyStats range:', dd_days[:3], '...', dd_days[-3:] if len(dd_days) > 3 else '', 'total', len(dd_days))
    P('--- dailyStats last 25 days (total permP casP) ---')
    for d in dd_days[-25:]:
        r = dd[d]
        P(d, '| total', r.get('total'), 'permP', r.get('permP'), 'casP', r.get('casP'))

with open(r'C:\Users\Salem Magdy\Desktop\LINAHSYSTEM\reports\meal_analysis.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(rep))
P('saved reports/meal_analysis.txt')